on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:
jobs:
  get-tempo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: GET EDF historicTEMPOStore 09-2022 - 08-2023
        run: |
          curl -H 'Accept-Charset: ascii' 'https://particulier.edf.fr/services/rest/referentiel/historicTEMPOStore?dateBegin=2023&dateEnd=2024' -o tempo_2024.json
      - name: Merge tempo_*.json and tempo.json
        run: |
          file -i tempo*json
          cat tempo_2024.json
          jq -s 'map(.dates |= map(select(.couleur != "NON_DEFINI"))) | unique_by(.dates[].date) | { "dates": map(.dates[])}' tempo_2024.json tempo.json > tempo_new.json
      - name: Replace old tempo.json file
        run: mv tempo_new.json tempo.json
      - name: Cleanup
        run: rm tempo_*.json
      - name: Commit file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update tempo.json
          branch: main
          file_pattern: "tempo.json"
